inhibit_all_warnings!

target "Grocr" do
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Eureka', '~> 2.0.0-beta.1'
end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!


